[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build -r"
  publish = "build"

[build.environment]
  NPM_FLAGS = "--version"

[functions]
  node_bundler = "esbuild"
